### ISSUE TITLE
Neues Safegame erstellen

### ISSUE THREAD

**Issue by marihe70** [Dueesberch/FarmingSimulatorLauncher#10]
Hallo, ich habe jetzt mit der neusten Version versucht ein neues Savegame mit einer neuen Map zu erstellen. Entweder mache ich was falsch oder es funzt nicht richitg. Ich habe die neue Map in die Mods importiert. Beim Klick auf Neu wurde die Karte auch im Auswahlmenü angezeigt. Danach habe ich die entsprechenden Mods ausgesucht. Es wurde alles ohne Fehler gespeichert. Ich habe aber keine Chance das Savegame zu starten. Wenn das entsprechende Savegame ausgesucht habe und auf Start klicke wird grundsätzlich das zuvor gespielte Savegame mit der vorherigen Karte gestartet. Auch bei einer Auswahl eines neuen Savegames im Spiel wird mir die neue Karte nicht angeboten. Für Hilfe bin ich sehr dankbar. MfG Mario

**Comment by Dueesberch** [comment]
Moin, also ich habe es gerade einmal getest. Ich kann das Savegame anlegen und dann den LS starten. Dann sind die Mods im LS verfügbar. Wie in der Anleitung beschrieben, gibt es dann leider noch kein Savegame im LS selber. Man muss also das Savegame im LS dann entsprechend erzeugen. Daran arbeite ich noch, aber es ist leider etwas aufwendig alle Dateien zusammen zu suchen die man bereitstellen muss.
Wir tasten uns mal an das Problem heran.
Wenn bei dir immer noch das alte Savegame vorhanden ist, scheint mit den Einstellungen etwas nicht zu stimmen. Wen der FSL gestartet wird wird der savegame1 Ordner (nach ein paar tests) gelöscht. Deshalb dürfte das alte Savegame eigentlich nicht mehr da sein. Ist der Pfad zu den LS Spieldaten korrekt? Standard ist ja `C:/Users/USER/Documents/My Games/FarmingSimulator2022/` ist das bei dir auch so? Wenn ja, steht der Pfad in den FSL Einstellungen?

Wurden beim ersten Start von FSL savegames und mods importiert?

**Comment by marihe70** [comment]
Hallo, es ist alles so wie du geschrieben. Alle Einstellungen sind korrekt. Ich wollte ja im LS ein neues Savegame erstellen. Es wird mir aber gar nicht die entsprechende Karte zur Auswahl angezeigt, obwohl diese beim FSL aktiviert wurde. Das SG 1 wurde gelöscht. Es sind auch alle Mods importiert. Ich habe es drei mal versucht. Vielen Dank.

**Comment by marihe70** [comment]
Ich habe gerade gesehen das im Ordner My Games/FarmingSimulator2022/ zweimal das Savegame 8, welches ich vorher gespielt hatte, abgelegt ist. Die müssen von FSL so angelegt worden sein. Soll das so sein?

**Comment by Dueesberch** [comment]
Moin, ich brauche mal einen Überblick, wie das bei dir alles gesetzt ist und was in welchen Ordnern liegt. Baue gerade ein kleines Tool dafür. Sollte morgen fertig sein. Hoffe du kannst dich noch so lange gedulden.

**Comment by marihe70** [comment]
Hallo, nicht hetzen es gibt bestimmt wichtigere Dinge. Ich habe es heute nochmal genau nach Anleitung gemacht. Die Mods werden beim Start all angeboten. Nur nicht die richtige Karte. Auch beim erstellen eines neuen Savegames wird die neue Karte nicht nageboten, obwohl dies importiert ist.

**Comment by Dueesberch** [comment]
Von welcher Map sprechen wir? Benutzt du Windows oder MacOS?

**Comment by marihe70** [comment]
Hallo, Windows.

**Comment by Dueesberch** [comment]
Kannst du bitte folgendes einmal ausführen:
1. [FSL_capture.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/8605511/FSL_capture.zip) entpacken
2. FarmingSimulatorLauncher starten
3. FarmingSimulatorLauncher beenden (Sollte einen "sauberes" Savegamesdataordner erzeugen)
4. FSL_capture.exe ausführen
5. Die Datei `fsl_capture.txt` vom Desktop hier anhängen
Damit kann ich mir mal die Struktur anschauen und wir kommen ein bisschen weiter bei der Fehlersuche.

Kannst du mir noch sagen, wie die Karte heißt und wo ich die evtl. herunterladen kann?

**Comment by marihe70** [comment]
Hallo, das ist die Thüringen 2.0, runtergeladen hab ich die bei Cornhub. Mittlerweile Habe ich den LS 22 deinstalliert und neu Installiert. Mein Sohn wollte spielen. Aber auch ohne FSL hat er nur die eine Karte + Standarkarten angezeigt. Es ging nichts mehr.

**Comment by Dueesberch** [comment]
Verstehe. Geht jetzt wieder alles? Hast du deine Sicherungen Mods und Savegames wieder eingefügt? Den FSL noch einmal probieren magst du wahrscheinlich nicht oder?

**Comment by marihe70** [comment]
Doch ich fang noch mal von vorne an. Es ist alles gesichert. Ich werde den FSL unbdingt noch mal neu aufsetzen. Vielleicht funzt es jetzt.

**Comment by Dueesberch** [comment]
Ok. Halt mich auf dem Laufenden. Bin sehr daran interessiert Fehler zu finden und den FSL stabiler zu machen.

**Comment by marihe70** [comment]
Mache ich, wird aber erst morgen.

**Comment by marihe70** [comment]
Guten Morgen, bevor ich den FSL wieder aktiviere stellt sich mir noch eine Frage. Folgender Sachverhalt: Ich spiele ein Savagame mit einer Modkarte. Es kommt von der Modkarte ein Update,  welches einen neuen Spielstand erfordert. Damit man nicht immer bei Updates bei Null anfangen muss, können einige Dateien aus dem alten Savegame, gesichert vor Update, in das neue SG übernommen werden. Wie verhält sich das bei der Benutzung des FSL? Weil der FSL erstellt ja immer ein SG 1, egal welche Modkarte benutzt wird. Wie kann ich hier einzelne Dateien aus einem SG alt in ein SG neu übernehmen??

**Comment by marihe70** [comment]
Hallo, ich habe es nun nach der Neuinstallation hinbekommen. Wer weiß was da schief gelaufen war. Auf jeden Fall geht es jetzt.

**Comment by Dueesberch** [comment]
Gut für dich schlecht für mich. Jetzt weiß ich nicht wo ich noch verbessern kann. 🙂
