### ISSUE TITLE
error when importing mods.

### ISSUE THREAD

**Issue by candymant** [Dueesberch/FarmingSimulatorLauncher#13]
i get this error window when i import mods
![error when importing](https://user-images.githubusercontent.com/47895720/179399529-236ce025-4189-4b43-8fc3-2c438e3ccb8c.jpg)
.

**Comment by candymant** [comment]
this is the mod causing the issue
[FS22_Tardis.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/9127680/FS22_Tardis.zip)
.

**Comment by Dueesberch** [comment]
Hi, thanks for your feedback.
I'm currently working at a new release. And there are already many changes in. So I reworked FSL to be able to import mods like tardis.
Attached you can find my current beta testing version. Hope it is working now. I'm sorry that the new features, changes and bugfixes not documented yet. I plan to create YT videos instead of writing manuals.
[FarmingSimulatorLauncher.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/9128515/FarmingSimulatorLauncher.zip)
.

**Comment by candymant** [comment]
I will test tommorow evening and let you know.

**Comment by candymant** [comment]
if i replace the launcher with the one you provided than i get not all my mods.
and if i want to import them. then i get an error if i select the mod map to import
![error when selecting map with mods to import](https://user-images.githubusercontent.com/47895720/179612691-88f9b3f2-bf89-4eef-b97e-3d4b87d33dae.jpg)
.

**Comment by candymant** [comment]
tardis i can import.

**Comment by Dueesberch** [comment]
Which mod failed? It seems there is a problem with the icon of the mod. I need to check

**Comment by candymant** [comment]
this is the mod causing the error
[LS22_fst990_Dinogas.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/9135738/LS22_fst990_Dinogas.zip)

**Comment by candymant** [comment]
i found the problem it was the mod itself in de moddesc the image file is icon.png but in the archive there was no icon .dss

**Comment by candymant** [comment]
the only problem for me right know is that my mods not all show if i switched the exe file with the one provided in this issue.

**Comment by candymant** [comment]
when i switch back to the previous they all show.

**Comment by Dueesberch** [comment]
the new version is checking for the ls version too. At the old version you will see all mods (fs19 / fs22), but at the new version you only see the mods according the selected version at FSL. Additionally the jhash value is checked. Is that already imported it will not import the new one. But I do not quarantee that there isn't still a bug or a not covered option. Can you do that [export list](https://www.groovypost.com/tips/print-contents-folder-windows-10/) and share the mods_db.json from your mods folder? So I can check what isn't imported and check why.

**Comment by Dueesberch** [comment]
https://discord.gg/AYyY68r2 guess that is a bit faster

**Comment by candymant** [comment]
I only get a black screen at discord.

Outlook voor Android downloaden<https://aka.ms/ghei36>
________________________________

**Comment by Dueesberch** [comment]
Interessting. So completely black? Than it seems a problem with the App / Browser.

**Comment by candymant** [comment]
Yes only 3 white stripes in the top left corner.



Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: Dueesberch ***@***.***>
Datum: 19/07/2022 13:01 (GMT+01:00)
Aan: Dueesberch/FarmingSimulatorLauncher ***@***.***>
Cc: candymant ***@***.***>, Author ***@***.***>
Onderwerp: Re: [Dueesberch/FarmingSimulatorLauncher] error when importing mods. (Issue #13)


Interessting. So completely black? Than it seems a problem with the App / Browser.

**Comment by candymant** [comment]
i see # general but get a message cant load messages

**Comment by candymant** [comment]
[listing and mods_db.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/9144093/listing.and.mods_db.zip)
in the zip are the 2 files you asked for

**Comment by Dueesberch** [comment]
Ok. The problem is that the import of the fst990 mod failed. But the mods_db.json is already created. So the creation dosn't rerun. I need to check how I can guarantee that the process is started again if it fails. As a workaround, you can remove the mods_db.json and start FSL again. If it fail again with another mod we need to fix that and do the job again.

**Comment by Dueesberch** [comment]
[FarmingSimulatorLauncher.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/9154126/FarmingSimulatorLauncher.zip)
Can you try that version. You should now get an popup with the failed mod and the traceback why.

**Comment by candymant** [comment]
i get many errors but not the fst990 mod
![Schermafbeelding 2022-07-20 234023](https://user-images.githubusercontent.com/47895720/180087299-4d20d9b7-c0fa-4333-a2cd-b1458862eea1.jpg)
![Schermafbeelding 2022-07-20 232356](https://user-images.githubusercontent.com/47895720/180087306-5b7bad00-9c05-4dcf-932c-9685f23a9a41.jpg)
![Schermafbeelding 2022-07-20 232434](https://user-images.githubusercontent.com/47895720/180087307-23cbfc45-ad6b-475e-9f8e-e71673574a87.jpg)
![Schermafbeelding 2022-07-20 232453](https://user-images.githubusercontent.com/47895720/180087310-a3559dd1-836c-4fdd-995b-07a383d330f2.jpg)
![Schermafbeelding 2022-07-20 232543](https://user-images.githubusercontent.com/47895720/180087311-f5ab4c4a-802a-46ae-84c0-feceabe18805.jpg)
![Schermafbeelding 2022-07-20 232614](https://user-images.githubusercontent.com/47895720/180087312-d23dad36-c982-41bd-9545-9bfc823175dd.jpg)
![Schermafbeelding 2022-07-20 232632](https://user-images.githubusercontent.com/47895720/180087315-e38a6a0e-d3df-4bc1-8b87-8e4dc82ebb82.jpg)
![Schermafbeelding 2022-07-20 232651](https://user-images.githubusercontent.com/47895720/180087317-7cfdef2c-a780-4607-9b6b-16e0a4a83623.jpg)
![Schermafbeelding 2022-07-20 232705](https://user-images.githubusercontent.com/47895720/180087318-768b7e73-78f9-459d-95fe-d4f6711a8bb7.jpg)
.

**Comment by candymant** [comment]
can you sent a new invite for discord

**Comment by candymant** [comment]
if i want to import them again then this error comes up
![Schermafbeelding 2022-07-21 000457](https://user-images.githubusercontent.com/47895720/180090677-9c25a583-daf0-4c68-a59c-3ee162402c14.jpg)
.

**Comment by Dueesberch** [comment]
[FarmingSimulatorLauncher.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/9157416/FarmingSimulatorLauncher.zip)
Guess I got it. Can you try?

**Comment by candymant** [comment]
Can you sent a new invite please maybe it works than.


Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows

Van: tommy ***@***.***>
Verzonden: dinsdag 19 juli 2022 15:11
Aan: ***@***.***>; ***@***.***>
CC: ***@***.***>
Onderwerp: RE: [Dueesberch/FarmingSimulatorLauncher] error when importing mods. (Issue #13)

Yes only 3 white stripes in the top left corner.



Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: Dueesberch ***@***.***>
Datum: 19/07/2022 13:01 (GMT+01:00)
Aan: Dueesberch/FarmingSimulatorLauncher ***@***.***>
Cc: candymant ***@***.***>, Author ***@***.***>
Onderwerp: Re: [Dueesberch/FarmingSimulatorLauncher] error when importing mods. (Issue #13)


Interessting. So completely black? Than it seems a problem with the App / Browser.

**Comment by Dueesberch** [comment]
https://discord.gg/CyqnwmZZ
