### ISSUE TITLE
Fehlermeldung beim neuen Savegame

### ISSUE THREAD

**Issue by Tomtiga1** [Dueesberch/FarmingSimulatorLauncher#2]
Moin, ich hab ein Problem, wenn ich ein Savegame erstellen möchte erscheint diese Meldung:
Danke im voraus!
![Unhandled exception in script 13 04 2022 21_03_33](https://user-images.githubusercontent.com/103602762/163252952-3713fc8d-0c1c-40ea-8ad3-7df353b610ce.png)

**Comment by Dueesberch** [comment]
Hallo, danke für dein Feedback. Einen Fehler im Code konnte ich schon identifizieren, aber um das Problem besser nachzustellen brauche ich ein paar mehr Infos. Hast du bereits Mods importiert? Kannst du mir einen Screenshot deiner Settings schicken?

**Comment by Tomtiga1** [comment]
Wenn ich Mods importieren möchte kommt die selbe Fehlermeldung.
![Einstellungen 13 04 2022 22_00_43](https://user-images.githubusercontent.com/103602762/163261234-706b5a13-b5b7-46f3-9c57-0321df3dc229.png)

**Comment by Dueesberch** [comment]
Danke. Ich schaue es mir schnellstmöglich an.

**Comment by Dueesberch** [comment]
Du hast FSL gesagt, dass er den fsl_all_mods-Ordner in deinem mods Ordner anlegen soll. Das kann nicht gehen, da der mods Ordner beim FSL Start immer neu erzeugt wird und somit der fsl_all_mods-Ordner weg ist. Ändere den Ordner mal auf `C:/Users/tommi/Documents/My Games/FarmingSimulator2022`. Danach sollte der Import aus deinem Modsbackup funktionieren. Ich werden im nächsten Release ein Prüfung einbauen.

**Comment by Tomtiga1** [comment]
Ok, danke! Ich werde es ausprobieren!

**Comment by Dueesberch** [comment]
Hat sich das Problem erledigt?

**Comment by Tomtiga1** [comment]
Ne leider irgendwie nicht. Wenn ich den Pfad so anpassen wie du es gezeigt hattest, dann kommt entweder wieder diese Fehlermeldung oder er findet halt keine Mods. Bin aber bis Freitag  nicht zu Hause, weswegen ich es erst in zwei Tagen wieder ausprobieren kann.

**Comment by Dueesberch** [comment]
Das er keine Mods mehr findet ist verständlich. FSL löscht den LS Modsordner bei jedem Start, damit eine saubere Basis vorhanden ist. Und damit natürlich auch deinen fsl_all_mods Ordner. Ich hoffe du hast wie in der Anleitung beschrieben deine Mods und savegames gesichert. Aus denen kannst du die Mods und Savegames wie in der Anleitung beschrieben importieren.

**Comment by Dueesberch** [comment]
Moin, hat sich das Problem geklärt?

**Comment by Tomtiga1** [comment]
Also ich muss ja beim ersten Start den Mod Ordner-Pfad angeben, und wenn ich den Pfad so angebe wie du es mir gezeigt hast, kommt wieder die Fehlermeldung
![Unhandled exception in script 25 04 2022 21_08_08](https://user-images.githubusercontent.com/103602762/165157292-3dfceffa-8d44-441c-be34-e301798a4e53.png)
.

**Comment by Dueesberch** [comment]
Passiert dies auch mit der neusten Version?
Kannst du den Ordner `C:/Users/BENUTZER//AppData/Roaming/FarmingSimulatorLauncher` einmal zippen und hier anhängen? (Drag&Drop)

**Comment by Tomtiga1** [comment]
Ich habs mit der aktuellsten Version ausprobiert. Leider ist aber die Zip zu groß, funktioniert weder hier noch auf Workupload.

**Comment by Dueesberch** [comment]
Also in dem Ordner sollten lediglich 3 kleine Dateien liegen. `fsl_settings.json, settings_fs22.json, games_fs22.json`. Zusammen sind die nicht mal 1 MB groß. Wenn das Zip des Ordners zu groß ist, ist da gewaltig was schief gelaufen. Kannst du einmal schauen, dass du den richtigen Ordner erwischt hast?

**Comment by Tomtiga1** [comment]
Ah sorry, dachte ich soll meinen normalen Farming Simulator Ordner... Hier der richtig
[FarmingSimulatorLauncher.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/8563291/FarmingSimulatorLauncher.zip)
e

**Comment by Dueesberch** [comment]
Kannst du die angehängte Datei entpacken und bitte in den Ordner `C:/Users/tommi/AppData/Roaming/FarmingSimulatorLauncher` kopieren und damit testen ob es startet? Der Pfad zu deinen Spieldaten war nicht vollständig.
[settings_fs22.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/8563494/settings_fs22.zip)

**Comment by Tomtiga1** [comment]
Ja hab ich gemacht. Nur jetzt ist noch das Problem dass er keine Mods findet. Welchen Ordner für die Mods soll ich denn auswählen bei den Einstellungen? Mein Backup-Ordner oder meinen normalen Mods Ordner?

**Comment by Tomtiga1** [comment]
Weil wenn ich den Farming Simulator Ordner angebe, so wie du es mir gesagt hast, kommt ne Fehlermeldung.

**Comment by Dueesberch** [comment]
Der fsl_all_mods Ordner dient zur Speicherung der importierten Mods. Wenn der unter `F:/Backup\` liegen soll passt es. Oder du gibst den Ordner `C:/Users/tommi/Documents/My Games` an. Dann legt FSL einen `fsl_all_mods_fs22` dort an. Du hattest beim ersten mal den Ordner in deinen mods Ordner gepackt. Aber der wird bei jedem Start ja gelöscht. Du musst also aus deinem Backup nochmal die Mods importieren. Das kannst du im Mods Fenster machen. https://github.com/Dueesberch/FarmingSimulatorLauncher/blob/main/manuals/manual_german.md#mods-importieren-oder-l%C3%B6schen

**Comment by Tomtiga1** [comment]
Ok alles klar, das hat bei mir etwas Licht ins Dunkle gebracht. Allerdings kommt, wenn ich die Mods unter dem Reiter "importieren", beim Ordner auswählen diese Fehlermeldung:
![Unhandled exception in script 26 04 2022 16_18_41](https://user-images.githubusercontent.com/103602762/165321261-2bf9dc9d-df23-43a0-95b0-2a93e6a62369.png)

**Comment by Dueesberch** [comment]
Da scheint einer der Mods nicht sauber programmiert zu sein. Ich pass da nochmal den FSL etwas an, damit man eine Info bekommt mit welchem Mod er Probleme hat. Komm ich aber erst später zu. Ich schreibe wenn eine neue Version verfügbar ist.
Aber Dank deiner Hilfe habe ich wieder 2 Punkte gefunden, die ich verbessern kann.

**Comment by Tomtiga1** [comment]
Alles klar, kann es evtl. auch  daran liegen dass paar Mods nicht gezippt sind?

**Comment by Dueesberch** [comment]
So. Ich hab mal 2 Prüfungen eingebaut. Eine um den XML Fehler abzufangen und eine um zu verhindern, dass der falsche Ordner mit den Savegames ausgewählt wird. Mod mit fehlerhafter moddesc.xml werden nicht importiert. FSL braucht zwingend die Version aus dem Mod. Könntest du die angehängte Version einmal testen und mir die Mods hier anhängen die als fehlerhaft erkannt werden?
[FarmingSimulatorLauncher_test.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/8569032/FarmingSimulatorLauncher_test.zip)

Entpackte Mods werden vom FSL wie auch beim LS nicht eingelesen. Dies verursacht also nicht das Problem. Ich denke da haben 1-2 Modder nicht sauber gearbeitet.

**Comment by Tritokx** [comment]
Ich habe fast genau das oben beschriebene Problem. Direkt beim ersten Start und der Einrichtung (also Auswahl der Pfade) kommt beim Klick auf Speichern:

_Traceback (most recent call last):
  File "G:\FarmingSimulatorLauncher_dev\src\fsl.py", line 514, in <module>
  File "G:\FarmingSimulatorLauncher_dev\src\fsl.py", line 486, in main
  File "settings.py", line 322, in guiSettings
  File "settings.py", line 222, in saveSettings
  File "settings.py", line 195, in checkPath
IndexError: list index out of range_

Beim Wegklicken der Meldung wird das Programm beendet. Getestet auch mit der gerade hier angebotenen Beta. Ein Mod sollte nicht die Ursache sein, bis zur Auswahl derer komme ich gar nicht. Und auch mit komplett leerem Mod-Ordner kommt diese Fehlermeldung.

Hinweis: Sowohl die FarmingSimulator22.exe als auch die Mods und Savegames liegen nicht im Standardpfad. Die exe liegt im Steam-Ordner auf meiner zweiten Festpaltte und auch der Dokumente-Ordner liegt auf dieser Platte.

**Comment by Dueesberch** [comment]
Moin, welchen Pfad gibst du den für den alle-mods-ordner an?

**Comment by Tritokx** [comment]
Den gleichen wie für die Savegames, so wie auch vom Programm vorgeschlagen.

D:/Users/meinsystemname/Documents/My Games/FarmingSimulator2022

Edit: Das war der entscheidende Hinweis. Hab jetzt dort einen Ordner "mods_alle" angelegt und den ausgewählt, jetzt klappt's. Danke!

Edit 2: Wenn ich das wie oben beschrieben mache, wird im Ordner "mods_alle" ein weiterer Ordner angelegt der leer bleibt und FSL findet bei der Einrichtung keine meiner Maps und Mods bei der Einrichtung.

**Comment by Tomtiga1** [comment]
> So. Ich hab mal 2 Prüfungen eingebaut. Eine um den XML Fehler abzufangen und eine um zu verhindern, dass der falsche Ordner mit den Savegames ausgewählt wird. Mod mit fehlerhafter moddesc.xml werden nicht importiert. FSL braucht zwingend die Version aus dem Mod. Könntest du die angehängte Version einmal testen und mir die Mods hier anhängen die als fehlerhaft erkannt werden? [FarmingSimulatorLauncher_test.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/8569032/FarmingSimulatorLauncher_test.zip)
> 
> Entpackte Mods werden vom FSL wie auch beim LS nicht eingelesen. Dies verursacht also nicht das Problem. Ich denke da haben 1-2 Modder nicht sauber gearbeitet.
>
Wenn ich es starte und dann auf "Mods" gehe, kommt diese Fehlermeldung
![Unhandled exception in script 27 04 2022 18_36_03](https://user-images.githubusercontent.com/103602762/165572326-318d1aff-60ae-4482-9820-c6532c02bbb8.png)
:

**Comment by Tomtiga1** [comment]
Kann man sehen welche Mods den Fehler machen? Kann ich das irgendwie beheben?

**Comment by Dueesberch** [comment]
Beim Import werden die Mods angezeigt die fehlerhaft sind. Diese dann gern mal hier anhängen.
ohne Programmiererfahrung konnte es schwierig werden die zu reparieren.

**Comment by Tomtiga1** [comment]
Problem ist ja ich kann keine Mods importieren.

**Comment by Dueesberch** [comment]
Auch mit dieser Version nicht?
[FarmingSimulatorLauncher_test.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/8575376/FarmingSimulatorLauncher_test.zip)

**Comment by Dueesberch** [comment]
Sorry habe dein letztes Fehlerfenster übersehen. Kannst du mal diese Version 
[FarmingSimulatorLauncher_findDefectMod.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/8575501/FarmingSimulatorLauncher_findDefectMod.zip)
 laufen lassen? Da sollte nachdem Crash im all_mods-Ordner eine Datei `getMods.txt` sein, in der der Mod steht der den Fehler verursacht. Diesen dann bitte einmal hier anhängen.

**Comment by Dueesberch** [comment]
Hast du discord?

**Comment by Tomtiga1** [comment]
Ja hab ich.

**Comment by Tomtiga1** [comment]
> Sorry habe dein letztes Fehlerfenster übersehen. Kannst du mal diese Version [FarmingSimulatorLauncher_findDefectMod.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/8575501/FarmingSimulatorLauncher_findDefectMod.zip) laufen lassen? Da sollte nachdem Crash im all_mods-Ordner eine Datei `getMods.txt` sein, in der der Mod steht der den Fehler verursacht. Diesen dann bitte einmal hier anhängen.
https://workupload.com/file/nY5k7b5x5GG

**Comment by Tomtiga1** [comment]
> Sorry habe dein letztes Fehlerfenster übersehen. Kannst du mal diese Version [FarmingSimulatorLauncher_findDefectMod.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/8575501/FarmingSimulatorLauncher_findDefectMod.zip) laufen lassen? Da sollte nachdem Crash im all_mods-Ordner eine Datei `getMods.txt` sein, in der der Mod steht der den Fehler verursacht. Diesen dann bitte einmal hier anhängen.

https://workupload.com/file/nY5k7b5x5GG

**Comment by Dueesberch** [comment]
Neuer Versuch:
[FarmingSimulatorLauncher_handledefectmods.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/8583561/FarmingSimulatorLauncher_handledefectmods.zip)

**Comment by Tomtiga1** [comment]
Ich habe es gerstern ohne die Fehlerhaften Mods probiert und ich konnte Mods etc. importieren.

**Comment by Dueesberch** [comment]
Das klingt doch schon mal gut. Wenn du magst kannst du jetzt noch mal die "fehlerhaften" probieren.

**Comment by Dueesberch** [comment]
Moin, kann ich den Issue schließen? Hattest du nochmal die Mods probiert, die Probleme bereitet haben?
