### ISSUE TITLE
Fehlermeldung beim ersten Start des FSL

### ISSUE THREAD

**Issue by SteWe95** [Dueesberch/FarmingSimulatorLauncher#3]
Moin, ich hab ein Problem, wenn ich den FSL zum ersten Mal starte erscheint die folgende Fehlermeldung: 
Danke im Voraus. Kann das vielleicht damit zu tun haben, das mein Windows Dokumente Ordner nicht wie im Standard auf Laufwerk C: liegt oder gibt es dafür eine andere Erklärung?
![grafik](https://user-images.githubusercontent.com/26544458/164104939-bbf22cb2-92f7-43a9-8410-bba683b7e7ec.png)

**Comment by Dueesberch** [comment]
Moin.
Also das der Dokumentenordner auf einem anderen Laufwerk liegt sollte nicht das Problem sein. Das Setup ist bei mir ebenfalls vorhanden.
Kleine Hintergrunderklärenung: Ich arbeite gerade an der Anzeige der Modbilder. Dafür musste ich leider mehrer Dateien / Namen von ls auf fs ändern. Das macht FSL aber automatisch.
Warum das Umbennen bei dir jetzt nicht sauber funktioniert hat ist die Frage.
Hast du das Release Exe heruntergeladen oder evtl. den Code geklont? Falls dir geklont nix sagt hast du die exe heruntergeladen. ;)
Ist das die erste Installation oder hast du bereits v1.0.0 benutzt?

**Comment by SteWe95** [comment]
Geklont habe ich das Repository auch, aber für die Installation habe ich die Release EXE verwendet.
Das ist meine erste Installation. Die v1.0.0 habe ich nicht verwendet.

**Comment by Dueesberch** [comment]
Moin, hab da noch einen Bug gefunden. Kannst du bitte das Release v1.1.1 probieren?

**Comment by SteWe95** [comment]
Ja werde ich heute Abend direkt mal machen!

**Comment by SteWe95** [comment]
Moin, ich bin ein bisschen weiter gekommen stehe aber nun vor der nächsten Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/26544458/164521061-f8ffa3eb-9608-4c5d-abc9-6fa1ed2fc9cd.png)

Ich hatte beim ersten Starten vergessen das Backup anzulegen und hatte den Start beim ersten mal dann bei der entsprechenden Abfrage beendet. 
Das ist bestimmt wieder nichts großes.

**Comment by Dueesberch** [comment]
Danke erstmal, dass du dir die Mühe machst es weiter zu probieren. Könntest du einmal die angehängte Version testen?
[FarmingSimulatorLauncher_test.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/8534270/FarmingSimulatorLauncher_test.zip)

**Comment by SteWe95** [comment]
Mit der Version läuft es jetzt.
DANKE für deine HIlfe

**Comment by Dueesberch** [comment]
Danke für dein Feedback

**Comment by marihe70** [comment]
Hallo, ich habe dieselbe Fehlermeldung wie oben. Gibt es eine Möglichkeit den FSL zurück zusetzen, damit man eine neue Installation machen kann?

**Comment by Dueesberch** [comment]
Hallo ein zurücksetzen ist noch nicht implementiert. Ist aber für die Zukunft geplant. Das hilft dir aber jetzt nicht.
Funktiert auch die letzte Version nicht?
Hat der erste Start mal funktioniert? Sprich konntest du schon einmal mods und savegames importieren? 
Hast du ein Backup angelegt?

**Comment by marihe70** [comment]
Hallo, nein es noch nicht funktioniert.

**Comment by marihe70** [comment]
Es wurde einmal der Modordner gelöscht wohin der gespeichert wurde, keine Ahnung. Dann kam die Fehlermeldung beim Versuch des Importierens, dass die Map nicht da wäre.

**Comment by Dueesberch** [comment]
Du kannst den Ordner C:/Users/BENUTZER//AppData/Roaming/FarmingSimulatorLauncher in C:/Users/BENUTZER//AppData/Roaming/FarmingSimulatorLauncher_bak umbenennen.
Der fsl_all_mods Ordner darf nicht im mods Ordner liegen. Das wird aber in der neusten Version aber geprüft.

**Comment by marihe70** [comment]
Guten Morgen, ich hab das heute früh vor Arbeitsbeginn nochmal probiert. Mit der V 1.1.2 kommt sofort der obige Fehler. Mit der V 1.0.0 läuft es jetzt. Eine andere Version hatte ich noch nicht runter geladen. Schönen Tag noch.

**Comment by Dueesberch** [comment]
Moin, ich bin jetzt etwas verwirrt. Die v1.1.2 soll eigentlich mehr Fehler abfangen und lösen. Da ich den FSL natürlich gerne stabil bekommen wurde, wäre es schön wen du mir ein paar Fragen beantworten könntest.
1. Welche der beiden oben genannten Meldungen kommt? Das er die games_fs22.json nicht findet? Oder die TypeError Meldung?
2. Hattes du den fsl_all_mods Ordner zuerst in den eigentlichen Mods Ordner gespeichert / gelegt?
3. Kannst du mir die Dateien aus `C:/Users/BENUTZER/AppData/Roaming/FarmingSimulatorLauncher` hier anhängen? (Ordner zippen und per drag&drop einfügen)
4. Kannst du mir die Dateien aus `C:/Users/BENUTZER/AppData/Roaming/FarmingSimulatorLauncher_bak` hier anhängen? (Odner zippen und per drag&drop einfügen)
5. Hast du nachdem die v1.0.0 lief die v1.1.2 probiert? Falls nein, könntest du dies bitte machen?

**Comment by marihe70** [comment]
Hallo,
zu 1 - Es kommt die Meldung mit dem TypeError
zu 2 - Nein, der Ordner war außerhalb des eigentlichen Modordners
zu 3 -
[FarmingSimulatorLauncher.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/8553790/FarmingSimulatorLauncher.zip)
zu 4 - 
[FarmingSimulatorLauncher_bak.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/8553813/FarmingSimulatorLauncher_bak.zip)
 zu 5 - Habe probiert. Kam der angesagte Fehler. Deshalb war die Nachfrage ob das ganze zurückgesetzt werden kann. Aber mit der Umbenennung ging es auch.

**Comment by Dueesberch** [comment]
Danke für deine Hilfe. Ich habe eine neu Version released. Mit dieser sollte dein Problem behoben sein und die kannst die letzen Anpassungen benutzen.

**Comment by marihe70** [comment]
Es funktioniert mit der neuen Version. Danke.
