### ISSUE TITLE
IndexError at checkPath

### ISSUE THREAD

**Issue by Dueesberch** [Dueesberch/FarmingSimulatorLauncher#5]
Den gleichen wie für die Savegames, so wie auch vom Programm vorgeschlagen.

D:/Users/meinsystemname/Documents/My Games/FarmingSimulator2022

Edit: Das war der entscheidende Hinweis. Hab jetzt dort einen Ordner "mods_alle" angelegt und den ausgewählt, jetzt klappt's. Danke!

Edit 2: Wenn ich das wie oben beschrieben mache, wird im Ordner "mods_alle" ein weiterer Ordner angelegt der leer bleibt und FSL findet bei der Einrichtung keine meiner Maps und Mods bei der Einrichtung.

_Originally posted by @Tritokx in https://github.com/Dueesberch/FarmingSimulatorLauncher/issues/2#issuecomment-1110253495_

**Comment by Dueesberch** [comment]
Bitte einmal
[FarmingSimulatorLauncher_test.zip](https://github.com/Dueesberch/FarmingSimulatorLauncher/files/8569022/FarmingSimulatorLauncher_test.zip)
 testen

**Comment by Tritokx** [comment]
Test läuft. Die Fehlermeldung am Anfang kam nicht mehr, alle Savegames ließen sich importieren. Mod-Zuordnung funktioniert wie erwartet und alles weitere auch, soweit ich das nach der kurzen Zeit beurteilen kann. Danke!
