### ISSUE TITLE
[Anregung] Alte Versionen löschen

### ISSUE THREAD

**Issue by Sacred-Shadow** [Dueesberch/FarmingSimulatorLauncher#9]
Es wäre nice, wenn in der Modverwaltung alte Versionen löschen könnte. 
Also einfacher als jetzt - am besten mit einem einfachen Knopf.

**Comment by Dueesberch** [comment]
Im Backlog gibt es den Punkt "Unbenutze Versionen finden". Wenn das implementiert wurde, kann man über eine Taste alle unbenutzen Versionen / Mods markieren und diese dann als Bulk löschen.
